version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_dev
    ports:
      - "5434:5432" # Mapeia a porta do container para seu PC
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sgm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # PersistÃªncia de dados

volumes:
  postgres_data:
